return {
  --[[ "saghen/blink.cmp", ]]
  --[[ version = "v0.*", ]]
  --[[ opts = { ]]
  --[[   keymap = { ]]
  --[[     preset = "default", ]]
  --[[     ["<C-k>"] = { "select_prev", "fallback" }, ]]
  --[[     ["<C-j>"] = { "select_next", "fallback" }, ]]
  --[[   }, ]]
  --[[   appearance = { ]]
  --[[     use_nvim_cmp_as_default = true, ]]
  --[[     nerd_font_variant = "mono", ]]
  --[[   }, ]]
  --[[   signature = { enabled = true }, ]]
  --[[ }, ]]
}
